### ISSUE TITLE
Change poll interval and timeout

### ISSUE THREAD

**Issue by cyberdock** [filewallio/chrome-extension#12]
Change poll interval to 3 seconds, timeout to 11 minutes

**Comment by TimothyBeene** [comment]
Currently I have two settings for this pollInterval and pollTimout. The pollTimout is just the number of attempts.

So I can set them to:
pollInterval : 3
pollTimout: 220 (3 * 220 = 11 minutes)

Otherwise I could go and implement a proper timeout. I guess there is a chance the pollInterval will can be late sometimes.

Speaking of what how do you want to handle a timeout / failed download?

**Comment by filewallio** [comment]
Good question :) Im not completely sure yet. I think the popup should at least show the download for some time, without the progress bar, and some indication that this download could not be converted. 
If the popup is not open we could use indicator.js to show some dialog thats styled like the "download intercepted" dialog and show some "sorry" message.
