### ISSUE TITLE
Show notification on icon if user is not logged in.

### ISSUE THREAD

**Issue by cyberdock** [filewallio/chrome-extension#8]
If the user is not yet logged in, the icon should show a yellow "?" via setBadgeText and setBadgeBackgroundColor.

**Comment by TimothyBeene** [comment]
Unfortunately chrome does not have the setBadgeTextColor and the default color is white so when I set the color to yellow the '?' is not readable. There is a way to do this that will require a moderate amount of work (using a HTML canvas to draw the icon with a badge then call setIcon). Otherwise I would recommend a darker color like 'DarkOrange' (see screenshot below)

Yellow background
![image](https://user-images.githubusercontent.com/16546441/75713344-44a58b80-5c8f-11ea-88c4-2c7c75e29682.png)

DarkOrange background
![image](https://user-images.githubusercontent.com/16546441/75713296-30fa2500-5c8f-11ea-9fbc-86475ca56d15.png)

**Comment by cyberdock** [comment]
Ah ok, i did not test this, then go for orange. Just don't use red, that looks like something is broken :)
